#!/usr/bin/env python3
"""Build HTML previews for numbered docs/resume markdown files."""

from __future__ import annotations

import html
from pathlib import Path

import markdown

ROOT = Path(__file__).resolve().parents[1]
PREVIEW = ROOT / "preview"

STYLE = (Path(__file__).resolve().parents[2] / "job/sail/preview/styles.css")

NAV = [
    ("index.html", "目录"),
    ("001-digital-employee-java-ai.html", "001"),
    ("002-tech-points-inventory.html", "002"),
    ("003-polished-external-copy.html", "003"),
]


def md_to_html(text: str) -> str:
    return markdown.markdown(
        text,
        extensions=["tables", "fenced_code", "sane_lists", "nl2br"],
    )


def wrap(title: str, body: str, active: str) -> str:
    nav = []
    for href, label in NAV:
        cls = "nav active" if href == active else "nav"
        nav.append(f'<a class="{cls}" href="{html.escape(href)}">{html.escape(label)}</a>')
    css = "../job/sail/preview/styles.css" if False else "styles.css"
    return f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{html.escape(title)}</title>
  <link rel="stylesheet" href="{css}">
</head>
<body>
  <header class="top"><div class="top-inner">
    <span class="brand">Arbor · resume</span>
    {''.join(nav)}
  </div></header>
  <main class="wrap"><article class="paper">
    <p class="kicker">numbered preview</p>
    {body}
  </article>
  <footer>对外粘贴用 003。001 / 002 是过程稿，不要直接投递。</footer>
  </main>
</body>
</html>
"""


def main() -> None:
    PREVIEW.mkdir(parents=True, exist_ok=True)
    sail_css = ROOT.parent / "job/sail/preview/styles.css"
    # styles.css is generated by sail builder; copy locally after that run
    files = [
        ("001-digital-employee-java-ai.md", "001 首版成稿"),
        ("002-tech-points-inventory.md", "002 技术点盘点"),
        ("003-polished-external-copy.md", "003 对外成稿"),
    ]
    for name, title in files:
        html_name = name.replace(".md", ".html")
        body = md_to_html((ROOT / name).read_text(encoding="utf-8"))
        (PREVIEW / html_name).write_text(wrap(title, body, html_name), encoding="utf-8")

    index = """
    <h1>项目口径预览</h1>
    <p class="note">与 get-job 交付包分开：这里是 Arbor 项目怎么写进简历，不是完整个人简历。</p>
    <div class="cards">
      <a class="card" href="001-digital-employee-java-ai.html"><div class="num">001</div><h2>首版成稿</h2><p>内部名偏多，仅作历史。</p></a>
      <a class="card" href="002-tech-points-inventory.html"><div class="num">002</div><h2>技术点盘点</h2><p>内部对照，勿粘进简历。</p></a>
      <a class="card" href="003-polished-external-copy.html"><div class="num">003</div><h2>对外成稿</h2><p>当前可粘贴版本。</p></a>
    </div>
    """
    (PREVIEW / "index.html").write_text(wrap("Arbor 项目口径预览", index, "index.html"), encoding="utf-8")
    if sail_css.exists():
        (PREVIEW / "styles.css").write_text(sail_css.read_text(encoding="utf-8"), encoding="utf-8")
    print(f"wrote {PREVIEW}")


if __name__ == "__main__":
    main()
